# Site Info
title: Dev Dad Blog
tagline: 'Confessions of a Failed Entrepreneur'
description: 'A Jekyll theme adapted from Lanyon.'
baseurl: ''
url: https://devdad10.github.io
logo: 'https://devdad10.github.io/public/logo.png'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: 'https://devdad10.github.io/blog/page:num'
permalink: pretty

version: 1.0.0

# About/contact
author:
  name: Dev Dad
  description: A passionate <strong>developer and researcher</strong>, learning to be a giant.
  gravatar: 0a4e753d3924937dd747b9f38f1418a6 # md5 hash of your email address
  contact:
    # linkedin:  https://www.linkedin.com/in/lizhihao
    github:    devdad10
    # facebook:  <hide>
    twitter:   devdad10
    # weibo:     <hide>
    # email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=

# Navigation (2nd level links supported)
nav:
  Home:           
    - 'https://devdad10.github.io/'
  Blog:           
    - 'https://devdad10.github.io/blog/'
    - { Categories: 'https://devdad10.github.io/blog/categories/' }
    - { Tags: 'https://devdad10.github.io/blog/tags/' }
  About:          
    - 'https://devdad10.github.io/about/'
  Github Project: 
    - 'https://devdad10.github.io/'

# Where are tags and categories displayed
tag_page: 'https://devdad10.github.io/blog/tags/'
category_page: 'https://devdad10.github.io/blog/categories/'

hero:
  image: https://devdad10.github.io/public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Plugins
# mathjax: true # whether support mathjax
# google_analytics_token: '' # leave blank if you don't want google analytics
# disqus_short_name: 'your_short_name' # leave blank if you don't want disqus

