# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:            EMCS LABS
tagline:          'EMCS LABORATORIES'
description:      ' --- description ---'
url:              http://emcslabs.github.io

author:
  name:           'EMCS LABS'
  url:            http://emcslabs.github.io
#  gravatar:
#  photo:
  introduction:   ' --- introduction ---'

paginate:         5
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/emcslabs/emcslabs.github.io
